version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres      
    ports:
      - '5432:5432'
    expose:
      - 5432

  test-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres      
    ports:
      - '5434:5432'
    expose:
      - 5434